import express from "express";
import authenticateUser from "../../middleware/authenticateUser.js";
import { allSentence, carbonReduction, companyUniverse, getCountriesByTable, renewables, saveSearch, sentenceGender, supplyChain, wasteAndRecycling, waterManagement, } from "../../controller/tool/index.js";
const toolRouter = express.Router();
toolRouter.get("/carbonSentence", authenticateUser, carbonReduction);
toolRouter.get("/wasteSentence", authenticateUser, wasteAndRecycling);
toolRouter.get("/waterSentence", authenticateUser, waterManagement);
toolRouter.get("/genderSentence", authenticateUser, sentenceGender);
toolRouter.get("/supplyChain", authenticateUser, supplyChain);
toolRouter.get("/renewablesSentence", authenticateUser, renewables);
toolRouter.get("/allSentence", authenticateUser, allSentence);
toolRouter.get("/companyUniverse", authenticateUser, companyUniverse);
toolRouter.post("/search", authenticateUser, saveSearch);
toolRouter.get("/countries", authenticateUser, getCountriesByTable);
export default toolRouter;
